---
title: "EDS 221 Day 4 Comp"
author: "Wylie Hampson"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

## Code warm up

```{r}
quarter_splits <- c(1.0, 1.1, 1.2, 1.1, 1.4, 1.5, 1.6, 1.4)
half_splits <- c(mode = "numeric", length = length(quarter_splits) - 1)

for (i in seq_along(quarter_splits) - 1) {
  half <- quarter_splits[i] + quarter_splits[i + 1]
  half_splits[i] <- half
}
half_splits
```

## Let's make some FUNctions!
### Basic function structure practice

```{r}
birddog_sum <- function(bird, dog) {
  
  if (bird > 50) {
    stop("Birds can't be greater than 50.")
  }
  
  if(bird < 10) {
    message("Cool little bird!")
  }
  
  if (dog < 0) {
    warning("Can a dog be less than 0 pounds?")
  }
  
  add_bird_dog <- bird + dog
  return(add_bird_dog)
}

bird4_dog5 <- birddog_sum(bird = 4, dog = 5)
bird4_dog5

birddog_sum(bird = 6, dog = -8)

# Causes an error
# birddog_sum(bird = "hwak", dog = 10)
```

```{r}
say_hello <- function(friend, weekday){
  print(paste0("Hello ", friend, ", have a great ", weekday, "!"))
}

say_hello(friend = "Bill", "Friday")

say_hello(6, "huh?")
```

## Print vs. Return

```{r}
find_multiple <- function(a, b) {
  my_multiplication <- a * b
  print(my_multiplication)
}

# Just prints, doesn't return. This shouldn't work in python
find_multiple(a = 10, b = 6)
```

## Functions with conditions

```{r}
animal_age <- function(animal, age) {
  
  if (!animal %in% c("dog", "goat")) {
    stop("Animal must be a dog of a goat.")
  }
  
  if (animal == "dog") {
    creature_age <- age * 7
  } else if (animal == "goat") {
    creature_age <- age * 4.7
  }
  return(creature_age)
}

animal_age("dog", 5)
animal_age("goat", 13)
# animal_age("donkey", 21)
```
The correct way.
```{r}
adelie_gentoo <- penguins %>% 
  filter(species %in% c("Adelie", "Gentoo"))
```

The wrong way of doing this.
```{r}
# This method alternately looks at Adelie, then Gentoo. Instead of looking for any entries in the species column that is Adelie or Gentoo.
adelie_gentoo_wrong <- penguins %>% 
  filter(species == c("Adelie", "Gentoo"))
```

## Functions with for loops

```{r}
df_means <- function(df) {
  for (i in 1:ncol(df)) { 
    col_mean <- mean(df[[i]], na.rm = TRUE)
    column_name <- colnames(df[i])
    print(paste("The mean value of", column_name, "is", col_mean))
  }
}

# colnames(df[i]) will return that column name as a string
# Update this function so that for each iteration it returns a phrase "The mean value of _____ is ______."

df_means(df = mtcars)
```

```{r}
# Make a subset of only structural size variables from the penguins dataset for chinstrap

chinstrap_sizes <- penguins %>% 
  filter(species == "Chinstrap") %>% 
  select(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g)

df_means(df = chinstrap_sizes)
```

## Condition to check class of an input

```{r}
lunchtime <- function(tacos, price_per) {
  
  # Could also use: if (is.numeric(tacos) == FALSE)
  if (!is.numeric(tacos)) {
    stop("tacos must be numeric")
  }
  
  tot_price <- tacos * price_per
  return(tot_price)
}

lunchtime(tacos = 5, price_per = 2.50)

# Gives an error
# lunchtime(tacos = "Yes Please", price_per = 3)
```













